GET http://localhost:3000/movies

###

GET http://localhost:3000/movies/65d281a203a2dd9e832751dd


###

POST http://localhost:3000/movies
Content-Type: application/json

{
    "name": "creed 1",
    "actor": "jordan3"
}

###

DELETE  http://localhost:3000/movies/65d281a203a2dd9e832751dd


###


PATCH  http://localhost:3000/movies/65d281a203a2dd9e832751dd
Content-Type: application/json

{
    "name": "New Name",
    "actor": "New Actor"
}
